name:                kwak-gui
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/monomer-starter#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
#category:
extra-source-files:
- README.md

default-extensions:
- ImportQualifiedPost
- OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - kwak-orth
  - data-default
  - lens
  - monomer
  - text
  - text-show

library:
  source-dirs:    src

executables:
  kwak-gui-text:
    source-dirs:      app-text
    main:             Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    dependencies:
    - kwak-gui
  kwak-gui-file:
    source-dirs:  app-file
    main:         Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    dependencies:
    - kwak-gui
